### ISSUE TITLE
Event name clashing on `<details>` element

### ISSUE THREAD

**Issue by gingerchew** [NigelOToole/tiny-ui-toggle#1]
Since the `<details>` element also has a "toggle" event. If you add the event listener below:

```js
document.querySelector('details.toggle-panel').addEventListener('toggle', ({ target }) => console.log(target.open));
```

When you open the panel, the console looks like this:
![image](https://user-images.githubusercontent.com/26461046/143886634-2826d1fa-2014-4367-8f48-7789b5cba85c.png)

Where as opening a normal `<details>` element would look like this:
![image](https://user-images.githubusercontent.com/26461046/143886844-780117b3-57ae-4c38-a437-be86c6ef9cb8.png)

I love that you added in animation for `<details>` since that is sorely needed.

**Comment by NigelOToole** [comment]
Thanks for pointing this out, I have made an update to the code to address this issue. If you want to listen for the toggle event of this plugin you can do so like this. `if (event.detail) console.log(`Action: ${event.detail.action}, Active: ${event.detail.active}`);` You can also listen for the normal details event as that still fires.
