### ISSUE TITLE
Escape key, focus for accessibility

### ISSUE THREAD

**Issue by seezee** [NigelOToole/tiny-ui-toggle#2]
The escape key should close the modals/overlays. Focus should remain inside the modal while it is open and should return to wherever it was before when the modal is closed.

See http://simplyaccessible.com/article/closing-modals/

**Comment by notoole-vccp** [comment]
Thanks for the issue, I have added escape support in the latest release.

**Comment by NigelOToole** [comment]
Thanks for the issue, this has been added to the 1.1 release.
